### ISSUE TITLE
Code for only one sensor

### ISSUE THREAD

**Issue by Anders-rosten** [jhschwartz/sm933X#1]
Hi
First of all, verry nice code you have made 👍 
Im verry new to I2C, 
My issue is, that I only need to use one sm9333!
Would you be so kind to explean, what I need to edit when I dont use a Multiplexer!
I have tryied for some time to modify your code witout any sucess.
It would really mean a lot to me,
All the best
Anders

**Comment by jhschwartz** [comment]
Hi @Anders-rosten,

I'm so so so sorry I didn't see this for almost 2 years. If you still need help with this please let me know and I'll take a look. Otherwise, I'm going to assume I'm too late to help. 

Best,
Jake

**Comment by jhschwartz** [comment]
It seems @bhelterline has made a non-multiplex version if that would be useful to you. 

https://github.com/bhelterline/sm933X
